### PR TITLE
Debian wheezy

### PR DESCRIPTION
**Pull request by dkowis**
I added support for Debian Wheezy to this, so I could use it :) I'm pretty sure I did the tests right, and I'm able to use it on my Wheezy box successfully.

### CODE REVIEW

**Comment by garethr** [comment]
Hi @dkowis, apologies it took me a while to get round to looking at this. Could you fix the two lint warnings that are shown in Travis? Sorry to be super picky.

The blockers are:

```
manifests/config.pp:21:arrow_alignment:WARNING:indentation of => is not properly aligned 
manifests/config.pp:21:unquoted_file_mode:WARNING:unquoted file mode
```

You can run this locally with either `bundle exec rake lint` or run the entire test suite with `bundle exec rake test` which checks lint, syntax and the rspec test suite.

**Comment by dkowis** [comment]
Yeah, I'll totally fix these within next week. Thanks for the feedback. I should have run the linter myself. 

On August 10, 2014 1:26:27 PM CDT, Gareth Rushgrove notifications@github.com wrote:

> Hi @dkowis, apologies it took me a while to get round to looking at
> this. Could you fix the two lint warnings that are shown in Travis?
> Sorry to be super picky.
> 
> The blockers are:
> 
> manifests/config.pp:21:arrow_alignment:WARNING:indentation of => is not
> properly aligned 
>   manifests/config.pp:21:unquoted_file_mode:WARNING:unquoted file mode
> 
> You can run this locally with either `bundle exec rake lint` or run the
> entire test suite with `bundle exec rake test` which checks lint,
> syntax and the rspec test suite.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/garethr/garethr-remotesyslog/pull/3#issuecomment-51722768

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dkowis** [comment]
Sorry this took so long for me to get back to. Things and such happened. `bundle exec rake test` doesn't complain at all, so hopefully it's good to go.

**Comment by garethr** [comment]
@dkowis thanks, much appreciated.

**Pull request merged**
